version: 2.1
defaults: &defaults
  docker:
    - image: cirrusci/flutter:1.22.5
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dart-dependencies-{{ checksum "pubspec.lock" }}
            - dart-dependencies-
      - run:
          name: Install Dependencies
          command: flutter pub get
      - save_cache:
          paths:
            - .dart_tool
          key: dart-dependencies-{{ checksum "pubspec.lock" }}
      - run:
          name: Analyze code
          command: flutter analyze
      - run:
          name: Run tests
          command: flutter test --coverage
      - run:
          name: Build Apk
          command: flutter build apk
